export const SAVEMELOGO = require('../assets/images/SavemeAppLogo.png');
export const BG_IMAGE = require('../assets/images/bgImage.png');
export const LOGIN_BG = require('../assets/images/loginscreenbackground.png');
export const GOOGLE = require('../assets/images/google.png');
export const APPLE = require('../assets/images/apple.png');
export const FACEBOOK = require('../assets/images/facebook.png');
export const BACK_ARROW = require('../assets/images/backArraw.png');
export const SAVEMETEXT = require('../assets/images/logoText.png');
export const LOCATION = require('../assets/images/location.png');
export const LOGO_LEAF = require('../assets/images/logoLeaf.png');
export const LOGO_LEAF2 = require('../assets/images/logoLeaf2.png');
export const MIRROR = require('../assets/images/mirror.png');
export const CHECKBOX = require('../assets/images/checkbox.png');
export const CLOSE = require('../assets/images/close.png');
export const HOMEL = require('../assets/images/homeL.png');
export const WORKL = require('../assets/images/workL.png');
export const MYACCOUNT = require('../assets/images/tab/ic_account.png');
export const ACTIVE_MYACCOUNT = require('../assets/images/tab/ic_activeAccount.png');
export const BOOKMARK = require('../assets/images/tab/ic_favourite.png');
export const ACTIVE_BOOKMARK = require('../assets/images/tab/ic_activeFavourite.png');
export const RECENT = require('../assets/images/tab/ic_recent.png');
export const ACTIVE_RECENT = require('../assets/images/tab/ic_activeRecent.png');
export const SEARCH = require('../assets/images/tab/ic_search.png');
export const ACTIVE_SEARCH = require('../assets/images/tab/ic_activeSearch.png');
export const ACTIVE_HOME = require('../assets/images/tab/ic_activehome.png');
export const HOME = require('../assets/images/tab/ic_home.png');
export const HOME_MODAL_IMAGE = require('../assets/images/homemodalImage.png');
export const FILTER_CATEGORY = require('../assets/images/filterCategory.png');
export const VIEWALLARROW = require('../assets/images/viewAllArrow.png');
export const FILL_RATESTAR = require('../assets/images/fillRateStar.png');
export const OREDER_PACKAGE = require('../assets/images/orderPackage.png');
export const DRIVER = require('../assets/images/driver.png');
export const PROMOCODE = require('../assets/images/promocode.png');
export const FOOD_INSTRUCTION = require('../assets/images/infoFood.png');
export const ROUND_RIGHT = require('../assets/images/roundRight.png');
export const SPOON = require('../assets/images/spoon.png');
export const TEST_FOOD_IMAGE = require('../assets/images/foodImageTest.jpg');
export const SHARE_ICON = require('../assets/images/shareIcon.png');
export const LOCATION_BORDER = require('../assets/images/locationBorder.png');
export const CLOCK = require('../assets/images/clock.png');
export const FAVBG = require('../assets/images/itemFavBg.png');
export const MINUS = require('../assets/images/remove.png');
export const PLUS = require('../assets/images/plus.png');
export const CREDITCARD = require('../assets/images/ic_creditCard.png');
export const CASHMONEY = require('../assets/images/ic_cashMoney.png');
export const APPLEPAY = require('../assets/images/ic_applePay.png');
export const EDITPENCIL = require('../assets/images/editPencil.png');
export const REFERFRIEND = require('../assets/images/referFriend.png');
export const SAVEMONEY = require('../assets/images/saveMoney.png');
export const CARBON = require('../assets/images/carbonFootPrint.png');
export const TC = require('../assets/images/t&c.png');
export const ABOUT = require('../assets/images/about.png');
export const CONTACT = require('../assets/images/contactUs.png');
export const PRIVACY = require('../assets/images/ic_privacy.png');
export const USER = require('../assets/images/ic_user.png');
export const BOLDRIGHTARROW = require('../assets/images/boldRightArraw.png');
export const CHECK = require('../assets/images/check.png');
export const ORDERCHECK = require('../assets/images/orderCheck.png');
export const ORDERCROSS = require('../assets/images/orderCross.png');
export const HOMEROUND = require('../assets/images/homeRound.png');
export const DRIVERPROFILE = require('../assets/images/driverProfile.png');
export const CALLICON = require('../assets/images/calIcon.png');
export const DELIVERED = require('../assets/images/delivered.png');
export const CUTLERYMODAL = require('../assets/images/cutleryModal.png');
export const EDIT = require('../assets/images/edit.png');
export const DELETE = require('../assets/images/delete.png');
export const LOCATIONPIN = require('../assets/images/locationPin.png');
export const WALLETICON = require('../assets/images/wallet.png');
export const ADDWALLET = require('../assets/images/addWallet.png');
export const REFER1 = require('../assets/images/refer1.png');
export const REFER2 = require('../assets/images/refer2.png');
export const REFER3 = require('../assets/images/refer3.png');
export const HOWITWORKS = require('../assets/images/howitwork.png');
export const IMG_1 = require('../assets/images/banners/Browse_Select_Img.png');
export const IMG_4 = require('../assets/images/banners/Congrats_Img.png');
export const IMG_2 = require('../assets/images/banners/Delivery_Pickup-Img.png');
export const IMG_5 = require('../assets/images/banners/Rate_Us_Img.png');
export const IMG_3 = require('../assets/images/banners/Scheduling_order.png');
export const RIGHT = require('../assets/images/awesome_arrow_circle_right.png');
export const LEFT = require('../assets/images/feather_skip_back.png');
export const DRIVERPIN = require('../assets/images/driverPin.png');
export const ESTIMATEDTIME = require('../assets/images/estimatedTime.png');
export const DELIEVRYFEE = require('../assets/images/deliveryFee.png');
export const SERVICEFEE = require('../assets/images/serviceFee.png');
// export const SPOON = require('../assets/images/spoon.png')
// export const SPOON = require('../assets/images/spoon.png')
// export const SPOON = require('../assets/images/spoon.png')
// export const SPOON = require('../assets/images/spoon.png')
export const LOGOIMAGE = require('../assets/logoImage.png')
export const OTPPAGEIMAGE = require('../assets/otpPageImage.png')
export const BACKBTN = require('../assets/backBtn.png')
export const SEARCHINPUT = require('../assets/search-normal.png')
export const ARROWRIGHT = require('../assets/arrow-right.png')
export const PARTNER_SIGNUP = require('../assets/user-group-man-man_hires.png')
export const CUSTOMER_SIGNUP = require('../assets/administrator-male_hires.png')
export const MENU = require('../assets/menu.png')
// export const SPOON = require('../assets/spoon.png')
// export const SPOON = require('../assets/spoon.png')
// export const SPOON = require('../assets/spoon.png')
// export const SPOON = require('../assets/spoon.png')
// export const SPOON = require('../assets/spoon.png')

